### ISSUE TITLE
Update to Unreal Enginge 5.4+

### ISSUE THREAD

**Issue by clanhall** [tolgee/tolgee-unreal#26]
Any chance to get an updated version for unreal 5.4+? It's not working well anymore ( as was here before
I'm getting infinite fetching with it.

https://forums.unrealengine.com/t/for-those-getting-no-log-result-in-gather-text-and-are-using-uinavigation3-0-plugin-in-ue5-2/1664719/2

**Comment by pasotee** [comment]
Test on 5.4.4 and an empty project set up according to the docs works as expected.

Fee free to re-open if you find any other issues.

**Comment by pasotee** [comment]
Also one more note on the issue linked from the Epic forum.

If you download Tolgee from the UE Marketplace/Fab and then use that as a base for future engine updates, as the forum comments mentioned, you need to update the `EngineVersion` field of the `.uplugin` file.

If you use Tolgee from GitHub, there is no `EngineVersion` field inside the `uplugin` because we don't distribute any precompiled binaries, therefore there is no potential compatibility issues.
